### ISSUE TITLE
Redesign the review cards on the profile page

### ISSUE THREAD

**Issue by nsunami** [nsunami/postreview-app#117]
While working on #115, I realized that we could potentially re-use the review cards on the article page on the profile page as well. Something like the below:

![image](https://user-images.githubusercontent.com/17035406/155134234-92e5bb62-eb3e-4766-8811-7738a95d1e58.png)

![image](https://user-images.githubusercontent.com/17035406/155134269-662bd6ca-22df-4527-86d6-33514b175edf.png)

Advantages would be:
1. We won't have texts for the submitted user, the submitted date, and the updated date to clutter the card (they will still be shown on hover to the icon)
2. The new design makes the visibility more noticeable since the avatar icon will change
3. By re-using the same card, we keep our code base simple.

**Comment by coglebed** [comment]
I really like this, good thinking!
