### ISSUE TITLE
[Bug]: cutting banner and log-in button

### ISSUE THREAD

**Issue by coglebed** [nsunami/postreview-app#130]
### URL of the Page

https://postreview-app.herokuapp.com/

### What happened?

Talked to a few people and it looks like people think that the banner on the landing page eats too much valuable space? And also another sign-in button is a little redundant given that there is another one above it. What do you think about cutting it like below?
![image](https://user-images.githubusercontent.com/73071333/156574871-4b47d96d-9d7c-400b-a46f-b67325563ab6.png)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nsunami** [comment]
I'm closing this issue for now since we are putting the search box and the browse paper buttons there (#163)
