### ISSUE TITLE
[Bug]: no way for logged-in users to view the landing page

### ISSUE THREAD

**Issue by coglebed** [nsunami/postreview-app#131]
### URL of the Page

https://postreview-app.herokuapp.com/

### What happened?

Another quick observation here - there is no way for users to view the landing page once they have logged in. That, by itself, is not a huge problem, but in our case - the landing page is the only place users can find instructions and examples on how to operate the website. Do you think we can add a link to the header for users to go back to landing? Or make a new page with instructions?

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nsunami** [comment]
Do we want a separate page showing how it works?
