### ISSUE TITLE
[Bug]: adding a new paper from the menu of the previously uploaded article treats new paper as already rated

### ISSUE THREAD

**Issue by coglebed** [nsunami/postreview-app#132]
### URL of the Page

https://postreview-app.herokuapp.com/articles/4a81abd3-94f4-491f-9d69-ae850faf4b89

### What happened?

Just added a paper while still hanging out on the page for the paper I've just submitted. Noticed that the menu in the newly uploaded paper is "edit rating", not "submit rating". Luckily, the bug is just visual and new paper rating editing does not affect the rating of the previously submitted paper.
![image](https://user-images.githubusercontent.com/73071333/156576270-67da0541-9baa-4540-8f50-0b63bb685c04.png)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nsunami** [comment]
I think this issue was fixed by #139—closing this for now.
