### ISSUE TITLE
Improve the "how it works" section 

### ISSUE THREAD

**Issue by nsunami** [nsunami/postreview-app#142]
How it works starts with "Pick a Paper". We want to indicate that the first action should indicate entering a DOI.

**Comment by coglebed** [comment]
![doi search postreview](https://user-images.githubusercontent.com/73071333/159299503-62107359-3ba8-4228-a6f5-5d6d6a41e586.png)
![doi search postreview cut](https://user-images.githubusercontent.com/73071333/159299732-07c60331-fdeb-4daf-bb77-ff545da813fa.png)
Not sure which image is better to replace the first screenshot with. We need to point users to the "search bar" at the top of the page and that "rate paper" button works in tandem with the search bar (it kind of looks like it's a standalone button doing something else currently)

**Comment by nsunami** [comment]
Fixed by #144
