### ISSUE TITLE
Hide articles without Reviews from the home page

### ISSUE THREAD

**Issue by nsunami** [nsunami/postreview-app#44]
When articles have no reviews, we want to hide them from the front-end so that they will not be shown to users. Still, we want to keep the article metadata in the articles table, to prevent duplicates.

This case happens when users delete their review for an article with only 1 review (their own review).

Thanks to @coglebed for the idea!
@all-contributors please add @coglebed for ideas.

**Comment by nsunami** [comment]
Addressing this issue would be a fix for #72 (clicking articles without reviews will lead to showing a review popup)

**Comment by coglebed** [comment]
I agree, it's hide empty articles from the home page. What if the user found it from the search? Would the pop-up initiate immediately similar to how it is now? That works as a solution for now, but my intuition tells me that we will develop a slightly different protocol in the future

**Comment by nsunami** [comment]
Yeah. Feel free to suggest another UX for a newly submitted article (on whimsical), or we can continue talking about this as well.
