### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by nsunami** [nsunami/postreview-app#59]
When I was working on the issue form (#58), I noticed that good practice is to have people agree with a code of conduct. But, we don't have a code of conduct set yet. I'm creating this issue to set a code of conduct.

As a first step, we want to decide whether we want to (1) create our own code of conduct or (2) adopt one of the available codes of conduct.
(@coglebed & @chartgerink: Do you have any thoughts around this?)

Resources
- [GitHub: Adding a code of conduct](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project)
- [Open Source Guide: Your Code of Conduct](https://opensource.guide/code-of-conduct/)

Example Code of Conducts
- [Contributor Covenant](https://www.contributor-covenant.org/)
- [Django](https://www.djangoproject.com/conduct/)
- [R=](https://www.notion.so/Code-of-Conduct-580ab64832a2478fad7d9dfad9d3da15)
- [BlitzJS](https://blitzjs.com/docs/code-of-conduct)
- and many more...

**Comment by chartgerink** [comment]
Hey @nsunami - thanks for inviting me for input.

If you're able to it is always worthwhile to consider what your values are going into this. I think the contributor covenant is a great and unambiguous starting point, if you're ready to uphold it. It will start the discussion from which you can customize in the future as you learn more and more about these things. 

The more people join, the more important a code of conduct is for your community..

**Comment by coglebed** [comment]
I checked out the Contributor Covenant and it looks good and fair to me!

**Comment by nsunami** [comment]
Update: we are moving forward with adopting the Contributor Covenant Code of Conduct for now. Let's close this issue, once the code of conduct gets merged.
