### ISSUE TITLE
[Bug]: Clicking on paper card initiates rating pop-up immediately

### ISSUE THREAD

**Issue by coglebed** [nsunami/postreview-app#72]
### URL of the Page

https://postreview-app.herokuapp.com/

### What happened?

 clicking on paper card initiates rating pop-up immediately
 I think this should be done manually once a person clicks the "submit a rating" button in the paper page

### Steps to reproduce

1. log in
2. click on any of the paper cards
3. the paper page loads
4. the pop-up instantly appears 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nsunami** [comment]
The reason why the app asks for a review is that the article does not have a review.
We can fix this by hiding articles without reviews on the home page (by addressing #44). 
I'm closing this for now and transferring to #44.
