### ISSUE TITLE
[Bug]: Cannot add a paper

### ISSUE THREAD

**Issue by chartgerink** [nsunami/postreview-app#73]
### URL of the Page

https://postreview-app.herokuapp.com/

### What happened?

I tried to rate a paper (DOI: `10.1525/collabra.71`) but nothing happened.

I checked the `devtools` and I got this error

```
Uncaught (in promise) ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "journal"
    ],
    "message": "Required"
  }
]
```

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nsunami** [comment]
@all-contributors please add @chartgerink for bug
