### ISSUE TITLE
[Bug]: empty ratings only have the Total score for them (misleading since it's not actually zero)

### ISSUE THREAD

**Issue by coglebed** [nsunami/postreview-app#84]
### URL of the Page

https://postreview-app.herokuapp.com/articles/1d38c6a6-124f-4ff6-a496-22d7bbd930f7

### What happened?

Other users' ratings on the paper page don't have subratings 
![image](https://user-images.githubusercontent.com/73071333/151014014-f7896ac4-5964-4704-973f-4f262f475dd2.png)

### Steps to reproduce

1. submit a review
2. get to the paper page

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nsunami** [comment]
I believe it was fixed in #91. Closing this issue for now. Feel free to reopen if that is not the case.
