### ISSUE TITLE
[Bug]: duplicate ratings in the profile page on paper cards

### ISSUE THREAD

**Issue by coglebed** [nsunami/postreview-app#88]
### URL of the Page

https://postreview-app.herokuapp.com/profile

### What happened?

Notice two different sets of ratings - either caused by different user's ratings or by my own previous edits or more than one submitted rating
![image](https://user-images.githubusercontent.com/73071333/151022485-17c89cd8-2f75-4efc-bd8e-9d46834e296e.png)

### Steps to reproduce

1. go to profile

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nsunami** [comment]
Fixed via #91

**Comment by coglebed** [comment]
Sweet! Good job
